config/routes.rb
Rails.application.routes.draw do

  resources :to_do_items do
    member do
      put :mark_done
      put :mark_removed
    end
  end


  resources :lists do
    resources :list_items do
      member do
        put :mark_read
        put :mark_removed
      end
    end
  end


  resources :list_items do
    member do
      put :mark_read
      put :mark_removed
    end
  end

  resources :knowledge_repositories

  devise_for :users
  root to: 'dashboard#show'
end

app/models/to_do_item.rb
# frozen_string_literal: true

class ToDoItem < ApplicationRecord
  belongs_to :user
  before_save :set_done_at, if: :done_changed?
  before_validation :set_valid_from
  before_validation :autolink
  validate :dates_validator

  # RED = RGB::Color.from_rgb(255, 0, 0)
  # YELLOW = RGB::Color.from_rgb(255, 255, 0)

  protected

  def autolink
    self.content = Rinku.auto_link(content)
  end

  def set_done_at
    self.done_at = done? ? DateTime.now : nil
  end

  def set_valid_from
    persisted? || valid_from.present? || self.valid_from = Date.today
  end

  def dates_validator
    if deadline.present? && (valid_from > deadline || deadline < Date.today)
      errors.add(:deadline, 'Deadline should be before valid_from and after now')
    end
  end
end

app/controllers/to_do_items_controller.rb
# frozen_string_literal: true

class ToDoItemsController < ApplicationController
  before_action :set_to_do_item, only: %i[show edit update destroy mark_done mark_removed]
  before_action :ensure_secure, except: %i[new index create]

  # GET /to_do_items
  # GET /to_do_items.json
  def index
    @to_do_items = current_user.to_do_items.all
  end

  # GET /to_do_items/1
  # GET /to_do_items/1.json
  def show; end

  # GET /to_do_items/new
  def new
    @to_do_item = ToDoItem.new
  end

  # GET /to_do_items/1/edit
  def edit; end

  # POST /to_do_items
  # POST /to_do_items.json
  def create
    @to_do_item = ToDoItem.new(to_do_item_params)
    @to_do_item.user_id = current_user.id

    respond_to do |format|
      if @to_do_item.save
        format.html { redirect_to @to_do_item, notice: 'To do item was successfully created.' }
        format.json { render :show, status: :created, location: @to_do_item }
        format.js
      else
        format.html { render :new }
        format.json { render json: @to_do_item.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /to_do_items/1
  # PATCH/PUT /to_do_items/1.json
  def update
    respond_to do |format|
      if @to_do_item.update(to_do_item_params)
        format.html { redirect_to @to_do_item, notice: 'To do item was successfully updated.' }
        format.json { render :show, status: :ok, location: @to_do_item }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @to_do_item.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT to_do_items/1/mark_done
  def mark_done
    @to_do_item.update(done: true)
    respond_to do |format|
      format.html { redirect_to to_do_items_url, notice: 'To do item was successfully marked done.' }
      format.json { head :no_content }
      format.js
    end
  end

  # PATCH/PUT to_do_items/1/mark_removed
  def mark_removed
    @to_do_item.update(removed: true)
    respond_to do |format|
      format.html { redirect_to to_do_items_url, notice: 'To do item was successfully marked removed.' }
      format.json { head :no_content }
      format.js
    end
  end

  # DELETE /to_do_items/1
  # DELETE /to_do_items/1.json
  def destroy
    @to_do_item.destroy
    respond_to do |format|
      format.html { redirect_to to_do_items_url, notice: 'To do item was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_to_do_item
    @to_do_item = ToDoItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def to_do_item_params
    params.require(:to_do_item).permit(:content, :done, :removed, :done_at, :description, :valid_from, :deadline)
  end

  def ensure_secure
    render file: 'public/401.html', status: :unauthorized unless @to_do_item.user == current_user
  end
end

app/helpers/to_do_items_helper.rb
# frozen_string_literal: true

module ToDoItemsHelper
  def urgency_color(to_do_item)
    if to_do_item.deadline.present? && to_do_item.valid_from.present?
      deadline = (DateTime.parse(to_do_item.deadline.to_s) + 1.day - 1.second).to_i
      valid_from = DateTime.parse(to_do_item.valid_from.to_s).to_i
      time_total = deadline - valid_from
      time_remaining = deadline - DateTime.now.to_i
      passed_share = 1.0 - time_remaining.to_f / time_total.to_f
      if passed_share > 0.5
        puts passed_share
        # average of red and yellow
        red = 255
        green = 255 - (passed_share - 0.5) * 2 * 255
        blue = 125 - passed_share * 125
      else
        green = red = 255
        blue = 255 - passed_share * 255
        puts blue
        puts passed_share
      end
      colors = [red, green, blue].map { |c| c.to_i.to_s(16).rjust(2, '0') }
      '#' + colors.join
    else
      'none'
    end
  end
end

app/views/to_do_items/_form.html.erb
<% async ||= false %>
<%= form_with(model: to_do_item, local: true, id: 'todo_form', data: {remote: async.to_s}) do |form| %>
  <% if to_do_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(to_do_item.errors.count, "error") %> prohibited this to_do_item from being saved:</h2>

      <ul>
      <% to_do_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if async %>
    <input name="_method" value="patch" type="hidden">
  <% end %>

  <div class="form-group">
    <%= form.label :content, for: :to_do_item_content %>
    <%= form.text_field :content, id: :to_do_item_content, size: 80, class: 'form-control' %>
  </div>

  <div class="form-group">
    <div class="form-check">
      <%= form.label :done, class: 'form-check-label', for: :to_do_item_done %>
      <%= form.check_box :done, id: :to_do_item_done, class: 'form-check-input' %>
    </div>
  </div>

  <div class="form-group">
    <div class="form-check">
    <%= form.label :removed, class: 'form-check-label' %>
    <%= form.check_box :removed, id: :to_do_item_removed, class: 'form-check-input' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, for: :to_do_item_description %>
    <%= form.text_area :description, id: :to_do_item_description, rows: 4, cols: 80, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :valid_from %>
    <input type="date" id="to_do_item_valid_from" name="to_do_item[valid_from]" value="<%= to_do_item.valid_from %>">
  </div>

  <div class="form-group">
    <%= form.label :deadline %>
    <input type="date" id="to_do_item_deadline" name="to_do_item[deadline]" value="<%= to_do_item.deadline %>">
  </div>

  <div class="actions">
    <%= form.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/to_do_items/_to_do_item.html.erb
<tr id="todo<%= to_do_item.id %>"
    class="to-do-item"
    title="<%= to_do_item.description %>"
    style="background-color: <%= urgency_color(to_do_item) %>">
  <td class="todo-content-container"><span title="<%= to_do_item.description %>" class="todo-content"><%= to_do_item.content.html_safe %></span></td>
  <% unless local_assigns.fetch(:dashboard, false) %>
    <td class="done"><%= to_do_item.done %></td>
    <td class="done-at"><%= to_do_item.done_at %></td>
    <td class="removed"><%= to_do_item.removed %></td>
  <% end %>
  <td class="date d-none d-md-block min">
    <%= humanize_date(to_do_item.created_at) %>
  </td>
  <td class="mark-done action"><%= link_to '✔', mark_done_to_do_item_path(to_do_item),
                  class: "btn badge badge-success badge-pill mark-read",
                  method: :put,
                  remote: true
  %></td>
  <!--td class="action"><%= link_to '📝', edit_to_do_item_path(to_do_item)%></td -->
  <td class="action" id="qpa">
    <%= button_tag '📝', type: 'button', class: 'btn btn-link action todo_edit small-line',
                   data: {toggle: 'modal', target: '#to_do_modal', class: 'to_do_item', whatever: "@getbootstrap", id: to_do_item.id} %>
  </td>
  <td class="action"><%= link_to '❌', mark_removed_to_do_item_path(to_do_item),
                                 method: :put,
                                 remote: true %></td>
</tr>

app/views/to_do_items/_to_do_item_list.html.erb
<a href=<%= to_do_items_path %>><h5>to do</h5></a>
<div class="col-sm-12 column no-side-padding">
  <table class="table sortable list no-bottom-margin table-striped" id="to-do">
    <tbody>
    <% @to_do_items.limit(10).each do |to_do_item| %>
      <%= render to_do_item, dashboard: true %>
    <% end %>
    </tbody>
  </table>
  <%= form_with(model: @new_to_do_item, class: 'form-inline') do |f| %>
    <div id="new-to-do">
      <%= f.text_field :content, class: 'small-text form-control', id: 'new-to-do-item', size: 80 %>
      <%= f.submit 'Quick add', class: 'small-text btn btn-primary btn-sm' %>
    </div>
  <% end if @new_to_do_item %>
  <br>
</div>

<script>
    autosizeInput(document.querySelector('#new-to-do-item'));
</script>

<%= render 'components/popup_form', name: 'to_do_modal' do %>
  <% render partial: 'to_do_items/form', locals: { to_do_item: ToDoItem.new, async: true } %>
<% end %>

app/views/to_do_items/create.js.erb
$("<%= escape_javascript(render @to_do_item, dashboard: true) %>").appendTo("#to-do tbody");
$( ".todo_edit" ).click(function() {
    var id = $(this).data("id");
    fill_form(id);
});
gon.to_do_item[<%= @to_do_item.id %>] = <%=raw @to_do_item.to_json %>;

app/views/to_do_items/destroy.js.erb
$(".to-do-list #id<%= @list_item.id %>").remove();

app/views/to_do_items/edit.html.erb
<h1>Editing To Do Item</h1>

<%= render 'form', to_do_item: @to_do_item %>

<%= link_to 'Show', @to_do_item %> |
<%= link_to 'Back', to_do_items_path %>

app/views/to_do_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>To Do Items</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Done</th>
      <th>Removed</th>
      <th>Done at</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @to_do_items.each do |to_do_item| %>
      <tr>
        <td><%= to_do_item.user_id %></td>
        <td><%= to_do_item.content %></td>
        <td><%= to_do_item.done %></td>
        <td><%= to_do_item.removed %></td>
        <td><%= to_do_item.done_at %></td>
        <td><%= to_do_item.description %></td>
        <td><%= link_to 'Show', to_do_item %></td>
        <td><%= link_to 'Edit', edit_to_do_item_path(to_do_item) %></td>
        <td><%= link_to 'Destroy', to_do_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New To Do Item', new_to_do_item_path %>

app/views/to_do_items/mark_done.js.erb
$("#to-do tbody #todo<%= @to_do_item.id %>").addClass('table-success');
$("#to-do tbody #todo<%= @to_do_item.id %> .mark-done").addClass("disabled");

app/views/to_do_items/mark_removed.js.erb
$("#todo<%= @to_do_item.id %>").remove();

app/views/to_do_items/new.html.erb
<h1>New To Do Item</h1>

<%= render 'form', to_do_item: @to_do_item %>

<%= link_to 'Back', to_do_items_path %>

app/views/to_do_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @to_do_item.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @to_do_item.content %>
</p>

<p>
  <strong>Done:</strong>
  <%= @to_do_item.done %>
</p>

<p>
  <strong>Removed:</strong>
  <%= @to_do_item.removed %>
</p>

<p>
  <strong>Done at:</strong>
  <%= @to_do_item.done_at %>
</p>

<p>
  <strong>Description:</strong>
  <%= @to_do_item.description %>
</p>

<%= link_to 'Edit', edit_to_do_item_path(@to_do_item) %> |
<%= link_to 'Back', to_do_items_path %>

app/views/to_do_items/update.js.erb
$('#to_do_modal').modal('hide');
$('#todo<%= @to_do_item.id %> .todo-content').text("<%= @to_do_item.content %>");