config/routes.rb
Rails.application.routes.draw do

  resources :to_do_items do
    member do
      put :mark_done
      put :mark_removed
    end
  end


  resources :lists do
    resources :list_items do
      member do
        put :mark_read
        put :mark_removed
      end
    end
  end


  resources :list_items do
    member do
      put :mark_read
      put :mark_removed
    end
  end

  resources :knowledge_repositories

  devise_for :users
  root to: 'dashboard#show'
end

app/models/list_item.rb
# frozen_string_literal: true

class ListItem < ApplicationRecord
  belongs_to :list
  OLD_DAYS = 1
  VERY_OLD_DAYS = 5
  before_save :fix_url
  before_save :set_description_placeholder
  after_create :set_description_as_title
  before_save :set_read_at, if: :read_changed?
  # TODO: validity conditions (e.g. read but no read date)

  protected

  def fix_url
    self.url = "http://#{url}" unless url[%r{\Ahttp://}] || url[%r{\Ahttps://}]
  end

  def set_description_placeholder
    self['description'] ||= self['url']
  end

  def set_description_as_title
    self['description'] = 
      open(self['url'])
        .read
        .scan(%r{<title>(.*?)</title>})
        .flatten
        .first
    save
  rescue StandardError => e
    Rails.logger.debug "Failed getting title for #{id}: #{url}"
    puts "Failed getting title for #{id}: #{url}"
    puts e
  end

  def set_read_at
    self.read_at = read? ? DateTime.now : nil
  end
end

app/controllers/list_items_controller.rb
# frozen_string_literal: true

class ListItemsController < ApplicationController
  before_action :set_list_item, only: %i[show edit update destroy mark_read mark_removed]
  before_action :set_list, only: [:create]
  before_action :ensure_secure, except: %i[new index]

  # GET lists/1/list_items
  # GET lists/1/list_items.json
  def index
    @list_items = ListItem
                  .where(list: current_user.lists)
                  .order(read: :asc, removed: :asc, created_at: :desc)
    if params[:list_id].present?
      @list_items = @list_items.where(list_id: params[:list_id])
    end
  end

  # GET lists/1/list_items/1
  # GET lists/1/list_items/1.json
  def show; end

  # GET lists/1/list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET lists/1/list_items/1/edit
  def edit; end

  # POST lists/1/list_items
  # POST lists/1/list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render :show, status: :created, location: @list_item }
        format.js
      else
        format.html { render :new }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT lists/1/list_items/1
  # PATCH/PUT lists/1/list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_item }
      else
        format.html { render :edit }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE lists/1/list_items/1
  # DELETE lists/1/list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to list_items_url, notice: 'List item was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  # PATCH/PUT lists/1/list_items/1/mark_read
  def mark_read
    @list_item.update(read: true, read_at: DateTime.now)
    respond_to do |format|
      format.html { redirect_to list_items_url, notice: 'List item was successfully marked read.' }
      format.json { head :no_content }
      format.js
    end
  end

  # PATCH/PUT lists/1/list_items/1/mark_removed
  def mark_removed
    @list_item.update(removed: true)
    respond_to do |format|
      format.html { redirect_to list_items_url, notice: 'List item was successfully marked removed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_list_item
    @list_item = ListItem.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_item][:list_id])
  end

  def list_item_params
    params.require(:list_item).permit(:url, :description, :read, :read_at, :removed, :list_id)
  end

  def ensure_secure
    list = @list_item&.list || List.find(params[:list_item][:list_id])
    render file: 'public/401.html', status: :unauthorized unless list.user == current_user
  end
end

app/helpers/list_items_helper.rb
# frozen_string_literal: true

module ListItemsHelper
  def list_item_row_class(list_item)
    if list_item.read
      'table-success'
    elsif (Date.today - list_item.created_at.to_date) > ListItem::VERY_OLD_DAYS
      'table-danger'
    elsif (Date.today - list_item.created_at.to_date) > ListItem::OLD_DAYS
      'table-warning'
    else
      'table-none'
    end
  end
end

app/views/list_items/_form.html.erb
<%= form_with(model: list_item, local: true) do |form| %>
  <% if list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% list_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :list_item_url, size: 80 %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :list_item_description, size: 80 %>
  </div>

  <div class="field">
    <%= form.label :read %>
    <%= form.check_box :read, id: :list_item_read %>
  </div>

  <div class="field">
    <%= form.label :read_at %>
    <%= form.datetime_select :read_at, id: :list_item_read_at %>
  </div>

  <div class="field">
    <%= form.label :removed %>
    <%= form.check_box :removed, id: :list_item_removed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/list_items/_list_item.html.erb
<tr id="id<%= list_item.id %>" class="<%= list_item_row_class(list_item) %>" >
  <td class="action"><img src="http://www.google.com/s2/favicons?domain_url=<%= list_item.url %>"></td>
  <td><a href="<%= list_item.url %>" target="_blank"><%= list_item.description %></a></td>
  <% unless local_assigns.fetch(:dashboard, false) %>
    <td class="read"><%= list_item.read %></td>
    <td class="read-at"><%= list_item.read_at %></td>
    <td class="removed"><%= list_item.removed %></td>
  <% end %>
  <td class="mark-read action"><%= link_to '✔', mark_read_list_item_path(list_item),
                  class: "btn badge badge-success badge-pill mark-read",
                  method: :put,
                  remote: true
  %></td>
  <td class="action"><%= link_to '📝', edit_list_item_path(list_item)%></td>
  <td class="action"><%= link_to '❌', mark_removed_to_do_item_path(list_item),
                                 method: :put,
                                 remote: true %></td>
</tr>

app/views/list_items/create.js.erb
$("<%= escape_javascript(render @list_item, dashboard: true) %>").appendTo("#<%= @list_item.list_id %>.list tbody");

app/views/list_items/destroy.js.erb
$("#id<%= @list_item.id %>").remove();

app/views/list_items/edit.html.erb
<h1>Editing List Item</h1>

<%= render 'form', list_item: @list_item %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'Back', list_items_path %>

app/views/list_items/index.html.erb
<div class="container">
  <div class="col-md-12">
    <h1>List Items</h1>

    <table class="table sortable">
      <thead>
        <tr>
          <th scope="col">Icon</th>
          <th scope="col">Content</th>
          <th scope="col">Read</th>
          <th scope="col">Read at</th>
          <th scope="col">Removed</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @list_items.each do |list_item| %>
          <%= render list_item %>
        <% end %>
      </tbody>
    </table>
    <%= form_with(model: @new_item) do |f| %>
        <%= f.text_field :url %>
        <%= f.submit 'Quick add' %>
    <% end if @new_item %>
    <br>

    <%= link_to 'New List Item', new_list_item_path %>
  </div>
</div>

app/views/list_items/mark_read.js.erb
$("#id<%= @list_item.id %>").removeClass('table-warning table-info');
$("#id<%= @list_item.id %>").addClass('table-success');
$("#id<%= @list_item.id %> .read").text('true');
$("#id<%= @list_item.id %> .mark-read").addClass("disabled");

app/views/list_items/mark_removed.js.erb
$("#id<%= @list_item.id %>").remove();

app/views/list_items/new.html.erb
<h1>New List Item</h1>

<%= render 'form', list_item: @list_item %>

<%= link_to 'Back', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @list_item.url %>
</p>

<p>
  <strong>Read:</strong>
  <%= @list_item.read %>
</p>

<p>
  <strong>Read at:</strong>
  <%= @list_item.read_at %>
</p>

<p>
  <strong>Removed:</strong>
  <%= @list_item.removed %>
</p>

<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>