config/routes.rb
Rails.application.routes.draw do

  resources :to_do_items do
    member do
      put :mark_done
      put :mark_removed
    end
  end


  resources :lists do
    resources :list_items do
      member do
        put :mark_read
        put :mark_removed
      end
    end
  end


  resources :list_items do
    member do
      put :mark_read
      put :mark_removed
    end
  end

  resources :knowledge_repositories

  devise_for :users
  root to: 'dashboard#show'
end

app/models/knowledge_repository.rb
# frozen_string_literal: true

class KnowledgeRepository < ApplicationRecord
  before_save :fix_url
  belongs_to :user

  protected

  def fix_url
    self.url = "http://#{url}" unless url[%r{\Ahttp://}] || url[%r{\Ahttps://}]
  end
end

app/controllers/knowledge_repositories_controller.rb
# frozen_string_literal: true

class KnowledgeRepositoriesController < ApplicationController
  before_action :set_knowledge_repository, only: %i[show edit update destroy]
  before_action :ensure_secure, except: %i[new index create]

  # GET /knowledge_repositories
  # GET /knowledge_repositories.json
  def index
    @knowledge_repositories = current_user.knowledge_repositories.all
  end

  # GET /knowledge_repositories/1
  # GET /knowledge_repositories/1.json
  def show; end

  # GET /knowledge_repositories/new
  def new
    @knowledge_repository = KnowledgeRepository.new
  end

  # GET /knowledge_repositories/1/edit
  def edit; end

  # POST /knowledge_repositories
  # POST /knowledge_repositories.json
  def create
    @knowledge_repository = KnowledgeRepository.new(knowledge_repository_params)
    @knowledge_repository.user_id = current_user.id

    respond_to do |format|
      if @knowledge_repository.save
        format.html { redirect_to @knowledge_repository, notice: 'Knowledge repository was successfully created.' }
        format.json { render :show, status: :created, location: @knowledge_repository }
      else
        format.html { render :new }
        format.json { render json: @knowledge_repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knowledge_repositories/1
  # PATCH/PUT /knowledge_repositories/1.json
  def update
    respond_to do |format|
      if @knowledge_repository.update(knowledge_repository_params)
        format.html { redirect_to @knowledge_repository, notice: 'Knowledge repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @knowledge_repository }
      else
        format.html { render :edit }
        format.json { render json: @knowledge_repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /knowledge_repositories/1
  # DELETE /knowledge_repositories/1.json
  def destroy
    @knowledge_repository.destroy
    respond_to do |format|
      format.html { redirect_to knowledge_repositories_url, notice: 'Knowledge repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_knowledge_repository
    @knowledge_repository = KnowledgeRepository.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def knowledge_repository_params
    params.require(:knowledge_repository).permit(:url, :description, :name)
  end

  def ensure_secure
    render file: 'public/401.html', status: :unauthorized unless @knowledge_repository.user_id == current_user.id
  end
end

app/helpers/knowledge_repositories_helper.rb
# frozen_string_literal: true

module KnowledgeRepositoriesHelper
end

app/views/knowledge_repositories/_form.html.erb
<%= form_with(model: knowledge_repository, local: true) do |form| %>
  <% if knowledge_repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(knowledge_repository.errors.count, "error") %> prohibited this knowledge_repository from being saved:</h2>

      <ul>
      <% knowledge_repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :list_item_name, size: 80 %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :list_item_url, size: 80 %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :list_item_description, size: 360 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/knowledge_repositories/edit.html.erb
<h1>Editing Knowledge Repository</h1>

<%= render 'form', knowledge_repository: @knowledge_repository %>

<%= link_to 'Show', @knowledge_repository %> |
<%= link_to 'Back', knowledge_repositories_path %>

app/views/knowledge_repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Knowledge Repositories</h1>

<table>
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @knowledge_repositories.each do |knowledge_repository| %>
      <tr>
        <td><%= knowledge_repository.name %> </td>
        <td><%= knowledge_repository.url %> </td>
        <td><%= link_to 'Show', knowledge_repository %></td>
        <td><%= link_to 'Edit', edit_knowledge_repository_path(knowledge_repository) %></td>
        <td><%= link_to 'Destroy', knowledge_repository, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Knowledge Repository', new_knowledge_repository_path %>

app/views/knowledge_repositories/new.html.erb
<h1>New Knowledge Repository</h1>

<%= render 'form', knowledge_repository: @knowledge_repository %>

<%= link_to 'Back', knowledge_repositories_path %>

app/views/knowledge_repositories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_knowledge_repository_path(@knowledge_repository) %> |
<%= link_to 'Back', knowledge_repositories_path %>